linux_task:
  container:
    image: gcc:latest
  env:
    CODECOV_TOKEN: f0a2eca9-3983-4103-a6f4-02b1caf4cbb5
  setup_script:
    - apt-get update
    - apt-get install -y --no-install-recommends valgrind ccache clang cmake
  build_script:
    - cd dev
    - make CC=gcc all
  test_script:
    - cd dev
    - make CC=gcc test
  test_optimized_script:
    - cd dev
    - make CC=gcc O=3 test
  test_nodebug_script:
    - ./configure --disable-rydb-debug
    - cd dev
    - make CC=gcc O=2 RYDB_DEBUG= test
    - make clean
  test_valgrind_script:
    - cd dev
    - make CC=gcc O=1 valgrind
  test_clang_sanitize_script:
    - cd dev
    - make O=2 CC=clang SANITIZE_ADDRESS_USE="" sanitize
  test_cmake_nodebug_script:
    - ./configure --disable-rydb-debug
    - cd dev
    - make O=2 cmake-test
  codecov_script:
    - cd dev
    - make clean
    - make CC=gcc coverage-gcc-create
    - bash <(curl -s https://codecov.io/bash)

osx_task:
  osx_instance:
    image: mojave-xcode-10.1
  test_cmake_script:
    - ./configure --enable-rydb-debug
    - make
    - cd tests
    - make CC=cc CCACHE="" static
    - make CC=cc CCACHE="" run
    - cd ../dev && make clean
  test_cmake_nodebug_script:
    - ./configure --disable-rydb-debug
    - make
    - cd tests
    - make CC=cc O=3 CCACHE="" static
    - make CC=cc O=3 CCACHE="" run
    - cd ../dev && make clean
  test_cmake_release_script:
    - ./configure --disable-rydb-debug --with-build-type=Release
    - make
    - cd tests
    - make CC=cc O=3 CCACHE="" static
    - make CC=cc O=3 CCACHE="" run
    - cd ../dev && make clean

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script: pkg install -y gmake cmake ccache
  test_script:
    - ./configure --enable-rydb-debug
    - cd dev
    - gmake test
  test_optimized_script:
    - ./configure --enable-rydb-debug
    - cd dev
    - gmake CCACHE="" O=3 test
  test_cmake_debug_script:
    - ./configure --enable-rydb-debug
    - cd dev
    - gmake CCACHE="" cmake-test
  test_cmake_release_script:
    - ./configure --disable-rydb-debug --with-build-type=Release
    - cd dev
    - gmake CCACHE="" cmake-test
 
