linux_task:
  container:
    image: gcc:latest
  env:
    CODECOV_TOKEN: f0a2eca9-3983-4103-a6f4-02b1caf4cbb5
    
  build_script: make CCACHE="" CC=gcc all
  tests_script: make CCACHE="" CC=gcc test
  coverage_script:
    - apt-get update
    - apt-get install -y --no-install-recommends python python-dev
    - wget https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install --user cpp-coveralls
    - pip install --user pyYAML
    - make CCACHE="" CC=gcc COVERAGE_VIEW="" coverage-gcc-create
    - /root/.local/bin/coveralls --exclude tests --gcov-options '\-lp'
#  coverage_script:
#    - make CCACHE="" CC=gcc COVERAGE_VIEW="" coverage-gcc-create
#    - bash <(curl -s https://codecov.io/bash)

osx_task:
  osx_instance:
    image: mojave-xcode-10.1
  test_script:
    - make CCACHE="" all
    - make CCACHE="" -C tests static
    - make CCACHE="" -C tests run

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script: pkg install -y gmake
  test_script: gmake CCACHE="" test
 
